### ISSUE TITLE
why the result of wam is worse than tfidf on KeywordPost.dat ?

### ISSUE THREAD

**Issue by lostfish** [YeDeming/THUTag#1]
**tfidf result**：
1 0.34649 0.01109 0.14729 0.00557 0.19949 0.00720 NaN NaN NaN NaN 4713
2 0.28808 0.00598 0.23600 0.00632 0.25104 0.00595 NaN NaN NaN NaN 7837
3 0.24602 0.00429 0.29840 0.00613 0.26183 0.00486 NaN NaN NaN NaN 10039
4 0.21399 0.00508 0.34317 0.00921 0.25679 0.00630 NaN NaN NaN NaN 11643
5 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
6 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
7 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
8 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
9 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
10 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
12747 68010 32387

**wam result**:
1 0.41113 0.01148 0.30217 0.00914 0.33617 0.00970 NaN NaN NaN NaN 3440
2 0.30428 0.00762 0.43326 0.01151 0.34415 0.00869 NaN NaN NaN NaN 5092
3 0.23871 0.00595 0.50488 0.01243 0.31286 0.00756 NaN NaN NaN NaN 5992
4 0.19487 0.00393 0.54636 0.01028 0.27813 0.00530 NaN NaN NaN NaN 6522
5 0.16395 0.00304 0.57300 0.01118 0.24760 0.00449 NaN NaN NaN NaN 6859
6 0.14179 0.00253 0.59378 0.01006 0.22290 0.00376 NaN NaN NaN NaN 7118
7 0.12479 0.00187 0.60909 0.00956 0.20216 0.00291 NaN NaN NaN NaN 7309
8 0.11105 0.00172 0.61922 0.01036 0.18417 0.00281 NaN NaN NaN NaN 7434
9 0.10065 0.00139 0.63091 0.01058 0.17005 0.00237 NaN NaN NaN NaN 7580
10 0.09195 0.00121 0.64035 0.01074 0.15774 0.00209 NaN NaN NaN NaN 7694
7694 12140406 11899

**run command**:
working_dir=$cur_dir/test_wam
report_file=$working_dir/report_wam.txt

java -Xmx5G -jar tagsuggest.jar evaluation.CrossValidator \
    --dataset=../traindata/KeywordPost.dat \
    --trainer_class=TrainWAM \
    --suggester_class=SMTKeywordTagSuggest \
    --num_folds=5 \
    --config="num_tags=10;norm=all_log;size=13702;dataType=KeywordPost;minwordfreq=10;mintagfreq=10;para=0.8" \
    --working_dir=$working_dir \
    --at_n=10 \
    --report=$report_file

Is there something wrong with my parameters? How can I reproduce the same results of readme ? Any help is appreciated.

**Comment by YeDeming** [comment]
With Md_2=2, your WAM got the result "precision=0.30428,recall=0.43326,fmean=0.34415"，which are "0.30735,0.43726,0.34747" in readme.  I am not really remember the best parameters.

Maybe you can try adjust "para=0.8" to "para=0.7" in "--config"， 

or adjust "minwordfreq" to remain words in original text whose frequency >= minwordfreq，

or adjust "mintagfreq" to let tags'  frequency be greater than mintagfreq.
